import express from 'express';
//-----------------------------------------------------------------------------------------------//
import { 
	requireLogin
} from '#middleware/auth.js';
import { 
	validate
} from '#middleware/validate.js';
//-----------------------------------------------------------------------------------------------//
import { 
	requireWorldEntered,
	requireCharacterCreated,
	requireNoCharacterCreated,
	requireToken
} from './middleware.js';
import {
	enterWorldSchema,
	createCharacterSchema,
	finishTurnSchema,
	reserveBuildingNameSchema,
	cancelBuildingNameSchema
} from './validation.js';
import {
	showEnterWorld,
	handleEnterWorld,
	showMenu,
	showCharacter,
	showCreateCharacter,
	handleCreateCharacter,
	showStartTurn,
	showManageBuildings,
	showManageEmploymentContracts,
	showManageRentalAgreements,
	showProduce,
	showTrade,
	showShare,
	showConsume,
	showManageGroup,
	handleFinishTurn,
	handleReserveBuildingName,
	handleCancelBuildingName,
	triggerProcessActions,
	showStatistics
} from './controller.js';

//===============================================================================================//

const router = express.Router();
//-----------------------------------------------------------------------------------------------//
router.get('/enter-world',
	requireLogin,
	showEnterWorld
);
//-----------------------------------------------------------------------------------------------//
router.post('/enter-world',
	requireLogin,
	validate(enterWorldSchema),
	handleEnterWorld
);
//-----------------------------------------------------------------------------------------------//
router.get('/',
	requireLogin,
	requireWorldEntered,
	showMenu
);
//-----------------------------------------------------------------------------------------------//
router.get('/character',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showCharacter
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/create-character',
	requireLogin,
	requireWorldEntered,
	requireNoCharacterCreated,
	showCreateCharacter
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/create-character',
	requireLogin,
	requireWorldEntered,
	requireNoCharacterCreated,
	validate(createCharacterSchema),
	handleCreateCharacter
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/start',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showStartTurn
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-buildings',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showManageBuildings
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-employment-contracts',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showManageEmploymentContracts
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-rental-agreements',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showManageRentalAgreements
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/produce',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showProduce
);//-----------------------------------------------------------------------------------------------//
router.get('/turn/trade',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showTrade
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/share',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showShare
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/consume',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showConsume
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-group',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	showManageGroup
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/finish',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	validate(finishTurnSchema),
	handleFinishTurn
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/reserve-building-name',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	validate(reserveBuildingNameSchema),
	handleReserveBuildingName
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/cancel-building-name',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated,
	validate(cancelBuildingNameSchema),
	handleCancelBuildingName
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/process-actions',
	//requireToken,
	triggerProcessActions
);
//-----------------------------------------------------------------------------------------------//
router.get('/statistics',
	requireLogin,
	requireWorldEntered,
	showStatistics
);

//===============================================================================================//

export default {
	path: '/game',
	router
};