import express from 'express';
//-----------------------------------------------------------------------------------------------//
import { 
	requireLogin
} from '#middleware/auth.js';
import { 
	requireValidation
} from '#middleware/validate.js';
//-----------------------------------------------------------------------------------------------//
import { 
	limitReserveBuildingNameRate,
	requireWorldEntered,
	requireCharacterCreated,
	requireToken
} from './middleware.js';
import {
	enterWorldSchema,
	createCharacterSchema,
	finishTurnSchema,
	checkTurnEditVersionSchema,
	reserveBuildingNameSchema,
	cancelBuildingNameSchema
} from './validation.js';
import {
	showEnterWorld,
	handleEnterWorld,
	showMenu,
	showCharacter,
	showCreateCharacter,
	handleCreateCharacter,
	showStartTurn,
	handleStartTurn,
	showManageBuildings,
	showManageEmploymentContracts,
	showManageRentalAgreements,
	showProduce,
	showTrade,
	showShare,
	showConsume,
	showManageGroup,
	showFinishTurn,
	handleFinishTurn,
	handleCheckTurnEditVersion,
	handleReserveBuildingName,
	handleCancelBuildingName,
	triggerProcessActions,
	showStatistics
} from './controller.js';

//===============================================================================================//

const router = express.Router();
//-----------------------------------------------------------------------------------------------//
router.get('/enter-world',
	requireLogin,
	showEnterWorld
);
//-----------------------------------------------------------------------------------------------//
router.post('/enter-world',
	requireLogin,
	requireValidation(enterWorldSchema),
	handleEnterWorld
);
//-----------------------------------------------------------------------------------------------//
router.get('/',
	requireLogin,
	requireWorldEntered,
	showMenu
);
//-----------------------------------------------------------------------------------------------//
router.get('/character',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showCharacter
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/create-character',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(false),
	showCreateCharacter
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/create-character',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(false),
	requireValidation(createCharacterSchema),
	handleCreateCharacter
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/start',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showStartTurn
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/start',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	handleStartTurn
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-buildings',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showManageBuildings
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-employment-contracts',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showManageEmploymentContracts
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-rental-agreements',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showManageRentalAgreements
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/produce',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showProduce
);//-----------------------------------------------------------------------------------------------//
router.get('/turn/trade',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showTrade
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/share',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showShare
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/consume',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showConsume
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/manage-group',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showManageGroup
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/finish',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	showFinishTurn
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/finish',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	requireValidation(finishTurnSchema),
	handleFinishTurn
);
//-----------------------------------------------------------------------------------------------//
router.post(
    '/turn/check-edit-version',
    requireLogin,
    requireWorldEntered,
    requireCharacterCreated(),
    requireValidation(checkTurnEditVersionSchema),
    handleCheckTurnEditVersion
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/reserve-building-name',
	limitReserveBuildingNameRate,
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	requireValidation(reserveBuildingNameSchema),
	handleReserveBuildingName
);
//-----------------------------------------------------------------------------------------------//
router.post('/turn/cancel-building-name',
	requireLogin,
	requireWorldEntered,
	requireCharacterCreated(),
	requireValidation(cancelBuildingNameSchema),
	handleCancelBuildingName
);
//-----------------------------------------------------------------------------------------------//
router.get('/turn/process-actions',
	//requireToken,
	triggerProcessActions
);
//-----------------------------------------------------------------------------------------------//
router.get('/statistics',
	requireLogin,
	requireWorldEntered,
	showStatistics
);

//===============================================================================================//

export default {
	path: '/game',
	router
};